# Normalization Problem

In this problem, a random 5x5 ndarray is generated and is to be normalized by using the functions .mean() and .std(). Accordingly, the first step is to import numpy as np to access the NumPy library, an expected output of a normalized generated random 5x5 ndarray will be created. Moreover, the normalized output is to be saved as a .npy.

The first step for this problem is to 'import numpy as np' to access the NumPy library.

In [3]:
#import from library the usage of np to shorten numpy
import numpy as np

In this part, a random 5x5 ndarray is generated and assigned to varaible X.

In [5]:
#create random 5x5 ndarray and store to variable X
X = np.random.random((5,5))

The variable X that stores the 5x5 ndarray is normalized in this part by centering and scaling. It is done by using X.mean() and X.std() to get the mean and standard deviation. To then normalized, the function (X - X_mean) / X_std to mimic the mathemical expression of normalizing is used and stored to X_normalized.

In [7]:
#centering and scaling
X_mean = X.mean()
X_std = X.std ()
X_normalized = (X - X_mean) / X_std

As specified in the problem, it is instructed to save the normalized X as 'X_normalized.npy'. To do so, the function np.save() is called. The name of the .npy file is first specified then it is followed by a coma then the syntax to be stored on the .npy file.

In [9]:
#saving normalized ndarray as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

To see the ouput, the function print() is used. The 'X' and 'X_normalized' are both printed to compare the original and normalized X.

In [11]:
#printing output for X and X_normalized
print("X: \n", X, "\n")
print("X_normalized: \n", X_normalized)

X: 
 [[0.60525288 0.19564226 0.73801624 0.9124942  0.25246208]
 [0.62980311 0.01042742 0.01187921 0.02287182 0.28372236]
 [0.28307086 0.7892252  0.87957138 0.23894653 0.47061118]
 [0.75063013 0.66976158 0.68635756 0.30550205 0.32438295]
 [0.4792204  0.15398249 0.55038128 0.15315932 0.29977106]] 

X_normalized: 
 [[ 0.65150082 -0.853072    1.13916427  1.7800529  -0.64436267]
 [ 0.74167819 -1.53339908 -1.5280664  -1.48768861 -0.52953808]
 [-0.53193117  1.32726393  1.65912154 -0.6940077   0.15693786]
 [ 1.18549737  0.88845274  0.94941276 -0.44953741 -0.38018448]
 [ 0.18856106 -1.00609573  0.44994764 -1.00911938 -0.47058835]]


# Divisible by 3 Problem

In this problem, a 10x10 ndarray which are the squares of the first 100 positive integers is created. Afterwards the elements that are divisible by 3 is to be identified and saved as 'div_by_3.npy'. Functions such as 'np.arrange' and 'np.reshape' are used. The positive integers are then squared by using '** 2'. To then determine the elements that are divisible by 3, modulo was used. Therefore, the overall expected output of the problem is to determine which of the elements among the first 100 squared integers are divisible by 3.

The first step for this problem is to 'import numpy as np' to access the NumPy library.

In [14]:
#import from library the usage of np to shorten numpy
import numpy as np

A ndarray, which are 1-100 is created and arranged. It is then reshape to a 10x10 array. Afterwards, each element is raised to 2 by using '** 2' and are stored to variable A.

In [16]:
#create 10x10 ndarray which are the squares of the first 100 positive integers
A = np.arange(1,101).reshape(10,10) ** 2

To determine the elements divisible by 3 in the first 100 squared integers, the elements in A should all equal to 0 when divided by 3 using modulo '%'. Afterwards, it is reshaped to a 3x11 array for better visualization and stored to the syntax 'div_by_3'.

In [18]:
#determining elements that are divisiable by 3
div_by_3 = A[A % 3 == 0].reshape(3,11)

As specified in the problem, it is instructed to save the elements divisible by 3 as 'div_by_3.npy'. To do so, the function np.save() is called again. The name of the .npy file is first specified then it is followed by a coma then the syntax to be stored on the .npy file.

In [20]:
#saving result as div_by_3.npy
np.save('div_by_3.npy', div_by_3)

To see the ouput, the function print() is used. The 'A' and 'div_by_3' are both printed to visualize which of the squared elements in A are divisible by 3 in div_by_three.

In [22]:
#print output for A and div_by_3
print("A: \n", A, "\n")
print("div_by_3: \n", div_by_3)

A: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 

div_by_3: 
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
