Normalization Problem

In [55]:
#import from library the usage of np to shorten numpy
import numpy as np

In [57]:
#create random 5x5 ndarray and store to variable X
X = np.random.random((5,5))

In [59]:
#centering and scaling
X_mean = X.mean()
X_std = X.std ()
X_normalized = (X - X_mean) / X_std

In [61]:
#saving normalized ndarray as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

In [63]:
#printing output for X and X_normalized
print("X: \n", X, "\n")
print("X_normalized: \n", X_normalized)

X: 
 [[0.80040672 0.32973291 0.18179031 0.15693766 0.77114793]
 [0.34888678 0.86430687 0.97035271 0.72040093 0.90434004]
 [0.80778366 0.12342295 0.15056592 0.13134584 0.98185714]
 [0.53895031 0.99183769 0.94044478 0.10173214 0.70106968]
 [0.16999023 0.29194855 0.69608408 0.05296093 0.2050129 ]] 

X_normalized: 
 [[ 0.84079456 -0.55721271 -0.99663559 -1.07045356  0.75388937]
 [-0.50032142  1.03059242  1.34557245  0.60315934  1.14949995]
 [ 0.86270573 -1.16999978 -1.08937905 -1.14646703  1.37974319]
 [ 0.06421011  1.40938767  1.25673915 -1.23442638  0.54574116]
 [-1.03168446 -0.66944078  0.5309328  -1.37928787 -0.92765927]]


Divisible by 3 Problem

In [65]:
#import from library the usage of np to shorten numpy
import numpy as np

In [111]:
#create 10x10 ndarray which are the squares of the first 100 positive integers
A = np.arange(1,101).reshape(10,10) ** 2

In [103]:
#determining elements that are divisiable by 3
div_by_3 = A[A % 3 == 0].reshape(3,11)

In [93]:
#saving result as div_by_3.npy
np.save('div_by_3.npy', div_by_3)

In [105]:
#print output for A and div_by_3
print("A: \n", A, "\n")
print("div_by_3: \n", div_by_3)

A: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 

div_by_3: 
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
